{"uid":"c1acd1035a22358","name":"Intentar registrar un dep贸sito en una cuenta inexistente","fullName":"Gesti贸n de transacciones: Intentar registrar un dep贸sito en una cuenta inexistente","historyId":"52f99f74a5a19b74a9526ca9b2087afa","time":{"start":1732867776112,"stop":1732867776114,"duration":2},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'user'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\transaction_manager_steps.py\", line 39, in step_impl\n    if context.user in accounts:\n       ^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'user'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\transaction_manager_steps.py\", line 39, in step_impl\n    if context.user in accounts:\n       ^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[{"name":"Given un usuario sin cuentas registradas","time":{"start":1732867776112,"stop":1732867776112,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When intenta depositar 500","time":{"start":1732867776112,"stop":1732867776114,"duration":2},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'user'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\transaction_manager_steps.py\", line 39, in step_impl\n    if context.user in accounts:\n       ^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Then se muestra un mensaje de error indicando cuenta inexistente","time":{"start":1732867776114,"stop":1732867776114,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"stepsCount":3,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Gesti贸n de transacciones"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"c1acd1035a22358.json","parameterValues":[]}